<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit10f57177870f89c47ea3ed98b31cb3c1
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Pods_Gravity_Forms\Prefixed\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Pods_Gravity_Forms\Prefixed\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit10f57177870f89c47ea3ed98b31cb3c1', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Pods_Gravity_Forms\Prefixed\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit10f57177870f89c47ea3ed98b31cb3c1', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Pods_Gravity_Forms\Prefixed\Composer\Autoload\ComposerStaticInit10f57177870f89c47ea3ed98b31cb3c1::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
