<?php

// autoload_static.php @generated by Composer

namespace Pods_Gravity_Forms\Prefixed\Composer\Autoload;

class ComposerStaticInit10f57177870f89c47ea3ed98b31cb3c1
{
    public static $prefixesPsr0 = array (
        'P' =>
        array (
            'Parsedown' =>
            array (
                0 => __DIR__ . '/..' . '/erusev/parsedown',
            ),
        ),
    );

    public static $classMap = array (
        'Pods_Gravity_Forms\\Prefixed\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Pods_Gravity_Forms__Prefixed__Parsedown' => __DIR__ . '/..' . '/erusev/parsedown/Parsedown.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit10f57177870f89c47ea3ed98b31cb3c1::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit10f57177870f89c47ea3ed98b31cb3c1::$classMap;

        }, null, ClassLoader::class);
    }
}
