<?php

// autoload-classmap.php @generated by Strauss

$strauss_src = dirname(__FILE__);

return array(
   'Pods_Gravity_Forms__Prefixed__Parsedown' => $strauss_src . '/erusev/parsedown/Parsedown.php',
);