name: 'PHP Compatibility'
on:
  pull_request:
    paths:
      - 'includes/**.php'
      - '*.php'
      - 'composer.json'
      - '.github/workflows/php-compatibility.yml'
jobs:
  phpcs-compatibility:
    uses: pods-framework/.github/.github/workflows/php-compatibility.yml@main
